### ISSUE TITLE
BLOG date, update

### ISSUE THREAD

**Issue by SLS-BLN** [SLS-BLN/capstone-user-stories#2]
**As a** user
**I need** to know how up to date the blog post is
**to be able to** to determine if I should read the post
 
## Description
 
<img width="300" alt="Screenshot 2022-07-18 at 09 54 34" src="https://user-images.githubusercontent.com/99472170/179478513-0de34472-95e2-4526-b5c2-55ac2ab0e8f7.png">

 
## Acceptance Criteria
 
- [ ] date of post
- [ ] update date of post (if updated)
 
## Tasks
  
(for developers team)
  
- [ ] update file structure (blog object)
- [ ] create a new date component

**Comment by actyvystom** [comment]
I just noticed that the following user stories also have the same issue:  

https://github.com/SLS-BLN/capstone-user-stories/issues/3
https://github.com/SLS-BLN/capstone-user-stories/issues/4
https://github.com/SLS-BLN/capstone-user-stories/issues/5 

as they all focus on a component rather than a screen.

We suggest first reworking this one and then discuss it again with you to clarify the other ones.
