### ISSUE TITLE
Tag component

### ISSUE THREAD

**Issue by SLS-BLN** [SLS-BLN/capstone-user-stories#3]
**As a** user
**I need** to see a tagline
**to be able to** quickly classify the topic
 
## Description
 
<img width="300" alt="Screenshot 2022-07-18 at 09 56 58" src="https://user-images.githubusercontent.com/99472170/179479790-20b49361-5697-4887-8a5d-289b7517dccd.png">

 
## Acceptance Criteria
 
- [ ] tagline
- [ ] colorsytem 
 
## Tasks
  
(for developers team)
  
- [ ] update file structure (blog object)
- [ ] create a new tag component
- [ ] create a list of tags - camera, audio, editing, etc.
- [ ] decide on the color scheme 
- [ ] storybook for the tag component
- [ ] write a test for the tag component
