### ISSUE TITLE
Image component

### ISSUE THREAD

**Issue by SLS-BLN** [SLS-BLN/capstone-user-stories#4]
## Value Proposition
 
As a user, 
I want to see a picture 
so I can decide if the topic interests me

## Description
 
<img width="200" alt="Screenshot 2022-07-18 at 09 57 19" src="https://user-images.githubusercontent.com/99472170/179486946-90868ea9-74b3-48d3-a077-a7c197541806.png">

 
## Acceptance Criteria
 
- [ ] photo
 
## Tasks
  
(for developers team)
  
- [ ] store images in a folder called "images" (public/images)
- [ ] assign an photoID to each image
- [ ] assign alt text to each image
- [ ] add photoID and alt-text to blog object (data structure)
- [ ] style: full viewport width, variable height
- [ ] write a test for the photo component
