### ISSUE TITLE
Header component

### ISSUE THREAD

**Issue by SLS-BLN** [SLS-BLN/capstone-user-stories#5]
## Value Proposition

As a user,
I want to see a short description of the content and a logo of the company,
So that I can know what the website is about

## Description
 
<img width="250" alt="Screenshot 2022-07-18 at 12 03 30" src="https://user-images.githubusercontent.com/99472170/179489273-e1b09b9c-882d-4486-8bc9-6e9c98e330a5.png">

 
## Acceptance Criteria
 
- [ ] short description of the company
- [ ] logo
 
## Tasks
  
(for developers team)
  
- [ ] export SVG logo of the company (Figma) - file name: logo.svg
- [ ] create Header component with logo and short description
- [ ] add Header component in App.js
- [ ] Storybook: add Header component
- [ ] test: check if Header component renders correctly
